[versions]
agp = "8.13.1"
appcompat = "1.7.1"
dependency-license-report = "2.9"
dependencycheck = "12.1.3"
dokka = "1.9.20"
java = "17"
json = "20250517"
kotlin = "2.1.21"
kotlinx-io = "0.5.4"
mavenPublish = "0.33.0"
mockito-inline = "5.2.0"
mockito-kotlin = "5.4.0"
mockk = "1.14.4"
multipaz = "0.95.0"
robolectricVersion = "4.15.1"
sonarqube = "6.2.0.5505"
kover = "0.9.1"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
json = { module = "org.json:json", version.ref = "json" }
kotlinx-io-bytestring = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-bytestring", version.ref = "kotlinx-io" }
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito-inline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
multipaz-android = { module = "org.multipaz:multipaz-android", version.ref = "multipaz" }
multipaz-android-legacy = { module = "org.multipaz:multipaz-android-legacy", version.ref = "multipaz" }
robolectric-robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectricVersion" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
dependency-license-report = { id = "com.github.jk1.dependency-license-report", version.ref = "dependency-license-report" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
